### PR TITLE
Translate quantifier weights to Boogie

### PR DESCRIPTION
**Pull request by fpoli**
With this PR Carbon translates quantifier weights (added in https://github.com/viperproject/silver/pull/633, used in https://github.com/viperproject/silicon/pull/674) to Boogie. I added a test to show how to set the weight in the AST.

### CODE REVIEW

**Comment by fpoli** [comment]
The following test fails in CI:
```
[info] - wands/examples/list_insert_tmp.vpr [carbon-Silver] *** FAILED *** (25 minutes, 46 seconds)
[info]   5 errors
[info]   
[info]   The following output occurred during testing, but should not have according to the test annotations:
[info]     [internal:internal] [internal:internal] An internal error occurred. Found 2 errors, but there should be 0. The output was: Boogie program verifier version 1.0.0.0, Copyright (c) 2003-2014, Microsoft.
[info]   Advisory: insert SKIPPED because of internal error: unexpected prover output: Broken pipe
[info]   /tmp/carbon8032009235638965007.bpl(956,11): Verification inconclusive (insert)
[info]   
[info]   Boogie program verifier finished with 3 verified, 0 errors, 1 inconclusive
[info]    (<no position>)
[info]     [internal:internal] [internal:internal] An internal error occurred. Found an unparsable output from Boogie: /tmp/carbon8032009235638965007.bpl(956,11): Verification inconclusive (insert) (<no position>)
[info]     [internal:internal] [internal:internal] An internal error occurred. Found an unparsable output from Boogie: Advisory: insert SKIPPED because of internal error: unexpected prover output: Broken pipe (<no position>)
[info]   
[info]   The following outputs was specified to occur erroneously (UnexpectedOutput) according to the test annotations, but did not occur during testing:
[info]     assert.failed:assertion.false (list_insert_tmp.vpr:132)
[info]     apply.failed:assertion.false (list_insert_tmp.vpr:90) (AnnotationBasedTestSuite.scala:63)
[info]   + Verifier used: carbon 1.0. 
[info]   + Time required: 73 msec (Parsing), 53 msec (Semantic Analysis), 19 msec (Translation), 87 msec (Consistency Check), 1545.99 sec (Verification). 
```

I failed to reprodue this error. Even when using the exact same Docker image `gobraverifier/gobra-base:v5_z3_4.8.7`, Boogie version `bae82d3`, and Z3 version `4.8.7` used in CI, `sbt test` runs fine and reports the following `CANCELED` message:
```
[info] - wands/examples/list_insert_tmp.vpr [carbon-Silver] !!! CANCELED !!! (16 seconds, 592 milliseconds)
[info]   2 ignored errors
[info]   apply.failed:assertion.false, issue 290
[info]   assert.failed:assertion.false, issue 290 (AnnotationBasedTestSuite.scala:81)
[info]   + Verifier used: carbon 1.0. 
[info]   + Time required: 1.29 sec (Parsing), 126 msec (Semantic Analysis), 180 msec (Translation), 310 msec (Consistency Check), 14.43 sec (Verification). 
[info] - wands/examples/list_sum_applyold.vpr [carbon-Silver] !!! IGNORED !!!
[info] - wands/examples/tree_delete_min_applyold.vpr [carbon-Silver] !!! IGNORED !!!
```

Strangely, running Carbon with `sbt run` fails for a completely different reason, related to macro expansion:
```
> sbt "run silver/src/test/resources/wands/examples/list_insert_tmp.vpr"
[info] welcome to sbt 1.6.2 (Private Build Java 17.0.5)
[info] loading global plugins from /home/fpoli/.sbt/1.0/plugins
[info] loading settings for project carbon-build from plugins.sbt ...
[info] loading project definition from /home/fpoli/src/carbon/project
[info] loading settings for project carbon from build.sbt ...
[info] loading settings for project silver from build.sbt ...
[info] set current project to Carbon (in build file:/home/fpoli/src/carbon/)
[warn] Compile / run / javaOptions will be ignored, Compile / run / fork is set to false
[info] running viper.carbon.Carbon silver/src/test/resources/wands/examples/list_insert_tmp.vpr
carbon 1.0
carbon found 1 error in 1.39s:
  [0] Parse error: Macro expansion would result in invalid code (encountered ParseTreeDuplicationError:)
Cannot duplicate PAccPred(PCall(PIdnUse(List),List(PIdnUse(crt)),None),PFullPerm()) with new children List(PCall(PIdnUse(List),List(PIdnUse(crt)),None), PFullPerm()) (list_insert_tmp.vpr@57.11)
```

**Comment by fpoli** [comment]
The failing test is in the `wands` folder. By removing *other* test folders the failing test passes.

My current best guess is that there is a deterministic memory leak in Carbon or in the test suite. When the CI runs out of memory, it might be that Z3 or Boogie is killed, which would explain the "broken pipe" error message. Then, Carbon or Boogie restarts the killed process and the remaining tests work fine.

I'm trying to identify the memory leak.

**Comment by fpoli** [comment]
Note: my quick mitigation 52c8642 is not thread-safe. Different verifier instances will data-race on it: one might call `ErrorMemberMapping.flush()` while the other verifier is still using the `ErrorMemberMapping`.

**Comment by fpoli** [comment]
My commit didn't solve the issue, but at least it got rid of the warning related to memory usage.
```
[warn] In the last 3101 seconds, 6.048 (0.2%) were spent in GC. [Heap: 0.91GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
```

**Comment by fpoli** [comment]
Since I recently gave too much attention to the encoding of quantifiers, magic wands became jalous and now demand to be tested before all other tests. Commit f73cb5b satisfies them, so that they now let the CI pass. Next time we'll have to buy them a pony, they said. :horse: 

This PR is ready for review @gauravpartha.

**Comment by gauravpartha** [comment]
As discussed in the meeting, we will look into merging this PR after the January 2022 release.

**Review by gauravpartha — APPROVED** [review]

**Pull request merged**
